additional_casks:
  # AI
  - claude-code

  # Browser
  - google-chrome

  # Video Call
  - zoom

  - loom

  # Notion
  - notion
  - notion-calendar
  - notion-mail

  # Communications
  - slack

  - clickhouse

