#!/bin/bash 

rosewater="0xfff5e0dc"
flamingo="0xfff2cdcd"
lavender="0xffb4befe"
base="0xff1e1e2e"

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="$lavender"
	inactive_color="$base"
    blacklist="Simulator"
)

borders "${options[@]}"
