#!/bin/bash 

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="Terminess Nerd Font"
PADDINGS=5

bar=(
  height=40
  color=$BAR_COLOR
  border_width=1
  border_color=$BAR_BORDER_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=8
  margin=10
  blur_radius=15
  corner_radius=9
  topmost=window
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:17.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Bold:16.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}" 

# Left 
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/stats.sh"

source "$ITEM_DIR/media.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
