#!/bin/zsh

# ==============================================================================
# GHOSTTY SHELL INTEGRATION FOR ZSH.
# ==============================================================================
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration"
fi

# ==============================================================================
# ZSH CONFIGURATION
# ==============================================================================

# History configuration
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups


# ==============================================================================
# CUSTOM AUTOLOADED FUNCTIONS
# ==============================================================================

# Lazy-load (autoload) Zsh function files from a directory.
ZFUNCDIR=${ZDOTDIR:-$HOME}/.zfunctions
fpath=($ZFUNCDIR $fpath)
autoload -Uz $ZFUNCDIR/*(.:t)
autoload -U colors && colors

jira_utils
jujutsu_utils

# ==============================================================================
# ZSH PLUGIN MANAGER
# ==============================================================================

source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza --long --color=always --icons=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza --long --color=always --icons=always $realpath'
zstyle ':fzf-tab:*' use-fzf-default-opts yes
zstyle ':fzf-tab:*' switch-group '<' '>'

# ==============================================================================
# KEY BINDINGS
# ==============================================================================

# Keybindings
bindkey -v
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^ ' autosuggest-accept

# Editor keybinding
autoload edit-command-line; zle -N edit-command-line 
bindkey '^e' edit-command-line

# ==============================================================================
# ALIASES
# ==============================================================================

alias vim=nvim
alias vi=nvim
alias ls='eza --long --color=always --icons=always'
alias gai='git add -i'
alias lld='lazydocker'
alias nb='newsboat'
alias ccal='calcurse'
alias ccals='calcurse-caldav'

# Jujutsu 
alias jbl='jj bookmark list -a'
alias jbmm="jj bookmark move -r 'trunk()' --to @-"
alias jgf='jj git fetch'
alias jgp='jj git push'
alias jl='jj log'
alias js='jj status'
alias jk='jj desc -m "$(koji --stdout)"'
alias jcc='jj commit -m "$(koji --stdout)"'
alias jc='jj commit'
alias je='jj edit'
alias jn='jj new'
alias jr='jj rebase -d @-'
alias jrm="jj rebase -d 'trunk()'"

alias jira='JIRA_API_TOKEN=$(pass Jira/AccessToken) jira'
alias note='jrnl'

# ==============================================================================
# THEME AND PROMPT
# ==============================================================================
_evalcache starship init zsh

# ==============================================================================
# TOOL INTEGRATIONS
# ==============================================================================

source <(fzf --zsh)

eval "$(pyenv init --path)"
eval "$(pyenv init - zsh)"
eval "$(pyenv virtualenv-init - zsh)"

_evalcache brew shellenv
_evalcache fnm env --use-on-cd --shell zsh
_evalcache rbenv init - zsh
_evalcache jenv init -
_evalcache zoxide init --cmd cd zsh
_evalcache jj util completion zsh
_evalcache jira completion zsh
# _evalcache kafkactl completion zsh


