#!/bin/zsh

# ==============================================================================
# ENVIRONMENT VARIABLES
# ==============================================================================

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export DISABLE_AUTO_UPDATE=true
export KEYTIMEOUT=1

export PERSONAL_HOME="$HOME/Code/Personal"
export WORK_HOME="$HOME/Code/Work"

export FZF_TMUX="1"
export EZA_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.conifg}/eza"

export PYENV_ROOT="$HOME/.pyenv"
export RBENV_ROOT="$HOME/.rbenv"
export JENV_ROOT="$HOME/.jenv"

export COLIMA_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}/colima"
export DOCKER_HOST="unix://${COLIMA_HOME}/default/docker.sock"

export EDITOR="nvim"
export TRANSIENT_PROMPT_TRANSIENT_PROMPT="❯ "

export HOMEBREW_BUNDLE_NO_UPGRADE=1
export PNPM_HOME="$HOME/.pnpm-global"
export PNPM_UTILS_HOME="$HOME/.pnpm-utils"

export RUSTUP_HOME="$HOME/.rustup"

export GPG_TTY=$(tty)

# NOTE: Uncomment the following to enable passing your GPG pin through STDIN. 
# export PASSWORD_STORE_GPG_OPTS="--pinentry-mode loopback --passphrase-fd 0"

