#!/bin/zsh

# ==============================================================================
# GHOSTTY SHELL INTEGRATION FOR ZSH.
# ==============================================================================
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration"
fi

# ==============================================================================
# Setting up our path
# ==============================================================================

HOMEBREW_PREFIX=$(brew --prefix)

typeset -gU path fpath
path=(
    $HOME/{,s}bin(N)
    $HOME/.local/{,s}bin(N)
    /opt/{homebrew,local}{,s}bin(N)
    /usr/local/{,s}bin(N)
    $HOME/.npm-global/bin(N)
    $HOME/.bin(N)
    $HOME/go/bin(N)
    $PYENV_ROOT/bin(N)
    $RBENV_ROOT/bin(N)
    $JENV_ROOT/bin(N)
    $PNPM_UTILS_HOME/node_modules/.bin(N)
    $PNPM_HOME(N)
    $HOME/.cargo/bin(N)
    $RUSTUP_HOME/bin(N)
    $path
)

# ==============================================================================
# ZSH CONFIGURATION
# ==============================================================================

# History configuration
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups


# ==============================================================================
# CUSTOM AUTOLOADED FUNCTIONS
# ==============================================================================

# Lazy-load (autoload) Zsh function files from a directory.
ZFUNCDIR=${ZDOTDIR:-$HOME}/.zfunctions

# ==============================================================================
# ZSH PLUGIN MANAGER
# ==============================================================================

# Set the root name of the plugins files (.txt and .zsh) antidote will use.
zsh_plugins=${ZDOTDIR:-~}/.zsh_plugins

# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Lazy-load antidote from its functions directory.
fpath=(
    $ZFUNCDIR(N)
    $HOMEBREW_PREFIX/opt/antidote/share/antidote/functions(N)
    $fpath
)

# autoload -Uz $ZFUNCDIR/*(.:t)
autoload -Uz antidote
autoload -U colors && colors

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh

# ====================================================================== 
# ZSH COMPLETIONS
# ====================================================================== 

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza --long --color=always --icons=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza --long --color=always --icons=always $realpath'
zstyle ':fzf-tab:*' use-fzf-default-opts yes
zstyle ':fzf-tab:*' switch-group '<' '>'

# ==============================================================================
# KEY BINDINGS
# ==============================================================================

# Keybindings
bindkey -v
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^ ' autosuggest-accept

if [[ -z "$NVIM" ]]; then 

    # Editor keybinding
    autoload edit-command-line; zle -N edit-command-line 
    bindkey '^e' edit-command-line
fi

# ==============================================================================
# ALIASES
# ==============================================================================

alias vim=nvim
alias vi=nvim
alias ls='eza --long --color=always --icons=always'
alias gai='git add -i'
alias lld='lazydocker'
alias nb='newsboat'
alias ccal='calcurse'
alias ccals='calcurse-caldav'
alias note='jrnl'

# Jujutsu 
alias jjk='jj desc -m "$(koji --stdout)" --edit'
alias jjcc='jj commit -m "$(koji --stdout)"'

# ==============================================================================
# THEME AND PROMPT
# ==============================================================================

_evalcache starship init zsh

source $HOMEBREW_PREFIX/share/zsh-transient-prompt/transient-prompt.zsh-theme

# ==============================================================================
# TOOL INTEGRATIONS
# ==============================================================================

zsh-defer -t 1 _evalcache fzf --zsh
zsh-defer -t 1 _evalcache pyenv init --path
zsh-defer -t 1 _evalcache pyenv virtualenv-init - zsh
zsh-defer -t 1 _evalcache pyenv init - zsh
zsh-defer -t 1 _evalcache fnm env --use-on-cd --shell zsh
zsh-defer -t 1 _evalcache brew shellenv
zsh-defer -t 1 _evalcache rbenv init - zsh
zsh-defer -t 1 _evalcache jira completion zsh

_evalcache zoxide init --cmd cd zsh
_evalcache jj util completion zsh
# _evalcache kafkactl completion zsh

if [ -s "$HOMEBREW_PREFIX/opt/jabba/jabba.sh" ]; then 
    zsh-defer -t 1 . "$HOMEBREW_PREFIX/opt/jabba/jabba.sh"
fi

if [ -f "$WORK_HOME/.work.zshrc" ]; then
    source "$WORK_HOME/.work.zshrc"
fi

