#!/bin/zsh

# ==============================================================================
# ENVIRONMENT VARIABLES
# ==============================================================================

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export DISABLE_AUTO_UPDATE=true
export KEYTIMEOUT=1

export PERSONAL_HOME="$HOME/Code/Personal"
export WORK_HOME="$HOME/Code/Work"

export FZF_DEFAULT_OPTS=" \
    --color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 \
    --color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
    --color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 \
    --color=selected-bg:#45475A \
    --color=border:#B4BEFE,label:#CDD6F4 \
    --border=bold"
export FZF_TMUX="1"

export JQ_COLORS="1;30:0;37:0;37:0;37:0;32:1;37:1;37:1;34"
export EZA_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.conifg}/eza"

export PYENV_ROOT="$HOME/.pyenv"
export RBENV_ROOT="$HOME/.rbenv"
export JENV_ROOT="$HOME/.jenv"

export COLIMA_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}/colima"
export DOCKER_HOST="unix://${COLIMA_HOME}/default/docker.sock"

export EDITOR="nvim"
export TRANSIENT_PROMPT_TRANSIENT_PROMPT="❯ "

export HOMEBREW_BUNDLE_NO_UPGRADE=1
export PNPM_HOME="$HOME/.pnpm-global"
export PNPM_UTILS_HOME="$HOME/.pnpm-utils"

export RUSTUP_HOME="$HOME/.rustup"

export GPG_TTY=$(tty)

# NOTE: Uncomment the following to enable passing your GPG pin through STDIN. 
# export PASSWORD_STORE_GPG_OPTS="--pinentry-mode loopback --passphrase-fd 0"

