--when.repositories = [
    "~/Code/Work",
    "~/Notes",
    "~/.password-store",
]

[user]
email = "joshua@oscilar.com"
name = "Josh Hamill"

[signing]
behavior = "drop"
backend = "gpg"
key = "Josh Hamill <joshua@oscilar.com>"

[git]
sign-on-push = true
