#!/bin/bash

if [[ -z $1 ]]; then 
    echo "Usage: launcher-switch <launcher-name>"
    echo ""
    exit 1
fi

LAUNCHERS_DIR="${XDG_CONFIG_HOME}/jhamill/launchers"
CURRENT_DIR="${XDG_STATE_HOME}/jhamill/current"

if [[ ! -d "$CURRENT_DIR" ]]; then 
    mkdir -p "$CURRENT_DIR"
fi
CURRENT_LAUNCHER="${CURRENT_DIR}/launcher"

LAUNCHER_NAME=$(echo "$1" | sed -E 's/<[^>]+>//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
LAUNCHER_PATH="${LAUNCHERS_DIR}/${LAUNCHER_NAME}"

if [[ ! -e "${LAUNCHER_PATH}" ]]; then 
    echo "Launcher '$LAUNCHER_NAME' does not exist"
    echo ""
    exit 1
fi

ln -nsf "$LAUNCHER_PATH" "$CURRENT_LAUNCHER"

